version: "3"

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ../:/workspace:cached
    ports:
      - "8080:8080"
    privileged: true
    tty: true
    stdin_open: true
